# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='protfolio_site',
            new_name='porfolio_site',
        ),
    ]
